language: php

php:
    - 7.3
    - 7.4
    - 8.0

env:
    - API_CLIENT_VERSION=^1.1
      VALUE_VERSION=^1.1
    - API_CLIENT_VERSION=^2.0
      VALUE_VERSION=^2.0

sudo: false

before_install:
    # Configure Xdebug 3.x.
    - echo 'xdebug.mode=coverage' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

    # Update & configure composer.
    - composer self-update --2
    - composer --version
    - composer config github-oauth.github.com ${GITHUB_TOKEN}
    - composer config --global --auth http-basic.digipolis.repo.repman.io token ${REPMAN_TOKEN}

    # Get the CodeClimate test reporter.
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

install:
    - composer require "digipolisgent/api-client:${API_CLIENT_VERSION}" --no-update --no-install --no-progress
    - composer require "digipolisgent/value:${VALUE_VERSION}" --no-update --no-install --no-progress
    - composer install -n --dev --no-progress

script:
    - vendor/bin/grumphp run

after_script:
    - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
